### ISSUE TITLE
Code difficult to follow

### ISSUE THREAD

**Issue by flamestar** [mozilla/calculator#91]
The code needs to follow some generic coding standards as it is extremely difficult to read. Adding in comments and or more documentation would be helpful.

**Comment by fwenzel** [comment]
Thank you for filing the issue. This kind of feedback is important to open source projects such as this.

However, this particular project is largely feature complete and also, the codebase is fairly simple so that there do not need to be extensive comments.

If there is a particular part of the code that you do not understand that you believe could benefit from a comment or better explanation, and if you're willing to submit a pull request adding that comment, please file a new Issue about that concrete issue.
